2025-03-22 17:49:04 collect.py [line:71] INFO: start checking whether existing subscriptions have expired
2025-03-22 17:49:05 utils.py [line:558] INFO: [Concurrent] multi-threaded execute [check_status] finished, count: 2, cost: 1.20s
2025-03-22 17:49:05 collect.py [line:113] INFO: load exists subscription finished, count: 2
2025-03-22 17:49:06 crawl.py [line:1430] INFO: [TelegramCrawl] starting crawl from telegram, channel: allv2board, pages: 19
2025-03-22 17:49:06 crawl.py [line:1390] INFO: [AirPortCrawl] start collect airport, url: https://t.me/s/allv2board?before=370
2025-03-22 17:49:06 crawl.py [line:1390] INFO: [AirPortCrawl] start collect airport, url: https://t.me/s/allv2board?before=350
2025-03-22 17:49:06 crawl.py [line:1390] INFO: [AirPortCrawl] start collect airport, url: https://t.me/s/allv2board?before=330
2025-03-22 17:49:06 crawl.py [line:1390] INFO: [AirPortCrawl] start collect airport, url: https://t.me/s/allv2board?before=310
2025-03-22 17:49:06 crawl.py [line:1390] INFO: [AirPortCrawl] start collect airport, url: https://t.me/s/allv2board?before=290
2025-03-22 17:49:06 crawl.py [line:1390] INFO: [AirPortCrawl] start collect airport, url: https://t.me/s/allv2board?before=270
2025-03-22 17:49:06 crawl.py [line:1390] INFO: [AirPortCrawl] start collect airport, url: https://t.me/s/allv2board?before=250
2025-03-22 17:49:06 crawl.py [line:1390] INFO: [AirPortCrawl] start collect airport, url: https://t.me/s/allv2board?before=230
2025-03-22 17:49:07 crawl.py [line:1390] INFO: [AirPortCrawl] start collect airport, url: https://t.me/s/allv2board?before=210
2025-03-22 17:49:07 crawl.py [line:1390] INFO: [AirPortCrawl] start collect airport, url: https://t.me/s/allv2board?before=190
2025-03-22 17:49:07 crawl.py [line:1390] INFO: [AirPortCrawl] start collect airport, url: https://t.me/s/allv2board?before=170
2025-03-22 17:49:07 crawl.py [line:1390] INFO: [AirPortCrawl] start collect airport, url: https://t.me/s/allv2board?before=150
2025-03-22 17:49:07 crawl.py [line:1390] INFO: [AirPortCrawl] start collect airport, url: https://t.me/s/allv2board?before=130
2025-03-22 17:49:07 crawl.py [line:1390] INFO: [AirPortCrawl] start collect airport, url: https://t.me/s/allv2board?before=110
2025-03-22 17:49:07 crawl.py [line:1390] INFO: [AirPortCrawl] start collect airport, url: https://t.me/s/allv2board?before=90
2025-03-22 17:49:08 crawl.py [line:1390] INFO: [AirPortCrawl] start collect airport, url: https://t.me/s/allv2board?before=70
2025-03-22 17:49:08 crawl.py [line:1390] INFO: [AirPortCrawl] start collect airport, url: https://t.me/s/allv2board?before=50
2025-03-22 17:49:08 crawl.py [line:1390] INFO: [AirPortCrawl] start collect airport, url: https://t.me/s/allv2board?before=30
2025-03-22 17:49:08 crawl.py [line:1390] INFO: [AirPortCrawl] start collect airport, url: https://t.me/s/allv2board?before=10
2025-03-22 17:49:09 utils.py [line:558] INFO: [Concurrent] multi-threaded execute [extract_airport_site] finished, count: 19, cost: 2.91s
2025-03-22 17:49:20 utils.py [line:558] INFO: [Concurrent] multi-threaded execute [get_redirect_url] finished, count: 14, cost: 10.68s
2025-03-22 17:49:26 utils.py [line:558] INFO: [Concurrent] multi-threaded execute [run_crawl] finished, count: 12, cost: 0.33s
2025-03-22 17:49:26 crawl.py [line:1731] INFO: [AirPortCollector] fetched 225 airport, start extracting real routing addresses
2025-03-22 17:50:15 utils.py [line:558] INFO: [Concurrent] multi-threaded execute [extract_backend_url] finished, count: 225, cost: 48.94s
2025-03-22 17:50:15 crawl.py [line:1743] INFO: [AirPortCollector] extract real base url finished, start to check it now
2025-03-22 17:50:56 utils.py [line:558] INFO: [Concurrent] multi-threaded execute [validate_domain] finished, count: 159, cost: 40.31s
2025-03-22 17:50:56 crawl.py [line:1755] INFO: [AirPortCollector] finished collect airport, availables: 33
2025-03-22 17:50:56 collect.py [line:267] INFO: start generate subscribes information, tasks: 35
2025-03-22 17:50:56 workflow.py [line:105] INFO: start fetch proxy: name=[DWhYIe2r]	id=[1]	domain=[http://sub.kjdjakskl.cyou]
2025-03-22 17:50:56 workflow.py [line:105] INFO: start fetch proxy: name=[UIqk2ipX]	id=[1]	domain=[http://sub.kjdjakskl.cyou]
2025-03-22 17:50:56 workflow.py [line:105] INFO: start fetch proxy: name=[hssl8088icu-d7n]	id=[1]	domain=[https://hssl8088.icu]
2025-03-22 17:50:56 workflow.py [line:105] INFO: start fetch proxy: name=[xjyjctop-2zc]	id=[1]	domain=[https://xjyjc.top]
2025-03-22 17:50:56 workflow.py [line:105] INFO: start fetch proxy: name=[chuifengjitop-6rbq]	id=[1]	domain=[https://chuifengji.top]
2025-03-22 17:50:56 workflow.py [line:105] INFO: start fetch proxy: name=[svipxingheyunsbs-630j]	id=[1]	domain=[https://svip.xingheyun.sbs]
2025-03-22 17:50:56 workflow.py [line:105] INFO: start fetch proxy: name=[thecomtoday-kq3g]	id=[1]	domain=[https://thecom.today]
2025-03-22 17:50:56 workflow.py [line:105] INFO: start fetch proxy: name=[wuxianjctop-omzsy]	id=[1]	domain=[http://wuxianjc.top]
2025-03-22 17:50:56 workflow.py [line:105] INFO: start fetch proxy: name=[pmy666xyz-itpr]	id=[1]	domain=[https://pmy666.xyz]
2025-03-22 17:50:56 workflow.py [line:105] INFO: start fetch proxy: name=[666vxyz-d4j9e]	id=[1]	domain=[https://666v.xyz]
2025-03-22 17:50:56 workflow.py [line:105] INFO: start fetch proxy: name=[kuailejcxyz-mwr2]	id=[1]	domain=[http://kuailejc.xyz]
2025-03-22 17:50:56 workflow.py [line:105] INFO: start fetch proxy: name=[changyouVPNtop-speu]	id=[1]	domain=[http://changyouVPN.top]
2025-03-22 17:50:56 workflow.py [line:105] INFO: start fetch proxy: name=[kuailejcxyz-xf1t]	id=[1]	domain=[https://kuailejc.xyz]
2025-03-22 17:50:56 workflow.py [line:105] INFO: start fetch proxy: name=[tuanzixyz-752az]	id=[1]	domain=[https://tuanzi.xyz]
2025-03-22 17:50:56 workflow.py [line:105] INFO: start fetch proxy: name=[bailiansite-32z4]	id=[1]	domain=[http://bailian.site]
2025-03-22 17:50:56 workflow.py [line:105] INFO: start fetch proxy: name=[cyousucc-r13qs]	id=[1]	domain=[https://c.yousu.cc]
2025-03-22 17:50:56 workflow.py [line:105] INFO: start fetch proxy: name=[xueyejiasucom-wm61]	id=[1]	domain=[http://xueyejiasu.com]
2025-03-22 17:50:56 workflow.py [line:105] INFO: start fetch proxy: name=[liulangdiqiucc-3erw]	id=[1]	domain=[https://liulangdiqiu.cc]
2025-03-22 17:50:56 workflow.py [line:105] INFO: start fetch proxy: name=[gladosspace-xvu]	id=[1]	domain=[https://glados.space]
2025-03-22 17:50:56 workflow.py [line:105] INFO: start fetch proxy: name=[panelkeleofficialcom-cpot]	id=[1]	domain=[https://panel.keleofficial.com]
2025-03-22 17:50:56 workflow.py [line:105] INFO: start fetch proxy: name=[a02qytvipaffpro-8ymlf]	id=[1]	domain=[https://a02.qytvipaff.pro]
2025-03-22 17:50:56 workflow.py [line:105] INFO: start fetch proxy: name=[fengwopro-gnrol]	id=[1]	domain=[https://fengwo.pro]
2025-03-22 17:50:56 workflow.py [line:105] INFO: start fetch proxy: name=[akpyunlive-g7dz9]	id=[1]	domain=[https://a.kpyun.live]
2025-03-22 17:50:56 workflow.py [line:105] INFO: start fetch proxy: name=[themeservercutecloudonede-kcfxm]	id=[1]	domain=[https://themeserver.cutecloudone.de]
2025-03-22 17:50:56 workflow.py [line:105] INFO: start fetch proxy: name=[bp123xyz-gji68]	id=[1]	domain=[https://bp123.xyz]
2025-03-22 17:50:56 workflow.py [line:105] INFO: start fetch proxy: name=[巅峰机场com-q7dp]	id=[1]	domain=[https://巅峰机场.com]
2025-03-22 17:50:56 workflow.py [line:105] INFO: start fetch proxy: name=[优惠机场com-r2mxc]	id=[1]	domain=[https://优惠机场.com]
2025-03-22 17:50:56 workflow.py [line:105] INFO: start fetch proxy: name=[aimanmanme-76x9]	id=[1]	domain=[https://aimanman.me]
2025-03-22 17:50:56 workflow.py [line:105] INFO: start fetch proxy: name=[snanguacom-ew6pb]	id=[1]	domain=[https://snangua.com]
2025-03-22 17:50:56 workflow.py [line:105] INFO: start fetch proxy: name=[便宜机场co-tls]	id=[1]	domain=[https://便宜机场.co]
2025-03-22 17:50:56 workflow.py [line:105] INFO: start fetch proxy: name=[yunduanjctop-tfo9]	id=[1]	domain=[https://yunduanjc.top]
2025-03-22 17:50:56 workflow.py [line:105] INFO: start fetch proxy: name=[changyouvpntop-e8yt5]	id=[1]	domain=[https://changyouvpn.top]
2025-03-22 17:50:56 workflow.py [line:105] INFO: start fetch proxy: name=[xn--wtq35pfyd55oco-pvuqc]	id=[1]	domain=[https://xn--wtq35pfyd55o.co]
2025-03-22 17:50:56 workflow.py [line:105] INFO: start fetch proxy: name=[xn--4oq11ryli3rgcom-yq4]	id=[1]	domain=[https://xn--4oq11ryli3rg.com]
2025-03-22 17:50:56 workflow.py [line:105] INFO: start fetch proxy: name=[wwwkuaidog006top-qs0vd]	id=[1]	domain=[https://www.kuaidog006.top]
2025-03-22 17:50:56 airport.py [line:276] INFO: achieved max retry when register, domain: https://巅峰机场.com
2025-03-22 17:50:56 airport.py [line:276] INFO: achieved max retry when register, domain: https://优惠机场.com
2025-03-22 17:50:56 airport.py [line:276] INFO: achieved max retry when register, domain: https://snangua.com
2025-03-22 17:50:56 airport.py [line:276] INFO: achieved max retry when register, domain: https://tuanzi.xyz
2025-03-22 17:50:56 airport.py [line:276] INFO: achieved max retry when register, domain: https://666v.xyz
2025-03-22 17:50:56 renewal.py [line:456] ERROR: fetch free plans error, cookies and authorization is empty, domain: https://glados.space
2025-03-22 17:50:56 airport.py [line:361] INFO: not exists free plan, domain: https://glados.space
2025-03-22 17:50:56 renewal.py [line:554] ERROR: query subscribe information error, cookies and authorization is empty, domain: https://glados.space
2025-03-22 17:50:56 airport.py [line:335] ERROR: [RegisterError] cannot get token when register, domain: https://glados.space
2025-03-22 17:50:56 airport.py [line:276] INFO: achieved max retry when register, domain: http://bailian.site
2025-03-22 17:50:56 airport.py [line:276] INFO: achieved max retry when register, domain: https://便宜机场.co
2025-03-22 17:50:56 airport.py [line:361] INFO: not exists free plan, domain: https://thecom.today
2025-03-22 17:50:56 airport.py [line:276] INFO: achieved max retry when register, domain: https://xn--4oq11ryli3rg.com
2025-03-22 17:50:56 airport.py [line:361] INFO: not exists free plan, domain: https://pmy666.xyz
2025-03-22 17:50:56 airport.py [line:276] INFO: achieved max retry when register, domain: https://yunduanjc.top
2025-03-22 17:50:56 airport.py [line:276] INFO: achieved max retry when register, domain: https://aimanman.me
2025-03-22 17:50:56 airport.py [line:276] INFO: achieved max retry when register, domain: http://wuxianjc.top
2025-03-22 17:50:56 airport.py [line:361] INFO: not exists free plan, domain: https://kuailejc.xyz
2025-03-22 17:50:56 airport.py [line:276] INFO: achieved max retry when register, domain: https://bp123.xyz
2025-03-22 17:50:56 airport.py [line:361] INFO: not exists free plan, domain: https://fengwo.pro
2025-03-22 17:50:56 airport.py [line:276] INFO: achieved max retry when register, domain: https://changyouvpn.top
2025-03-22 17:50:56 airport.py [line:276] INFO: achieved max retry when register, domain: https://hssl8088.icu
2025-03-22 17:50:57 airport.py [line:361] INFO: not exists free plan, domain: https://chuifengji.top
2025-03-22 17:50:57 airport.py [line:361] INFO: not exists free plan, domain: https://xjyjc.top
2025-03-22 17:50:57 airport.py [line:276] INFO: achieved max retry when register, domain: http://kuailejc.xyz
2025-03-22 17:50:57 airport.py [line:276] INFO: achieved max retry when register, domain: http://changyouVPN.top
2025-03-22 17:50:57 airport.py [line:276] INFO: achieved max retry when register, domain: https://c.yousu.cc
2025-03-22 17:50:57 airport.py [line:276] INFO: achieved max retry when register, domain: https://panel.keleofficial.com
2025-03-22 17:50:57 airport.py [line:276] INFO: achieved max retry when register, domain: https://xn--wtq35pfyd55o.co
2025-03-22 17:50:57 airport.py [line:361] INFO: not exists free plan, domain: https://a02.qytvipaff.pro
2025-03-22 17:50:57 airport.py [line:361] INFO: not exists free plan, domain: https://liulangdiqiu.cc
2025-03-22 17:50:58 airport.py [line:276] INFO: achieved max retry when register, domain: https://themeserver.cutecloudone.de
2025-03-22 17:50:58 airport.py [line:361] INFO: not exists free plan, domain: http://xueyejiasu.com
2025-03-22 17:50:58 airport.py [line:364] INFO: found free plan, domain: https://www.kuaidog006.top, plan: Plan(plan_id=12, package='month_price', renew=True, reset=False, trafficflow=100)
2025-03-22 17:50:58 renewal.py [line:607] ERROR: cannot get subscribe information, domain: https://a02.qytvipaff.pro, response: <!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>访问提示</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }
        .container {
            background-color: #ffffff;
            padding: 40px;
            border-radius: 8px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            text-align: center;
        }
        h1 {
            color: #333333;
        }
        p {
            color: #555555;
            margin: 20px 0;
        }
        a.button {
            display: inline-block;
            padding: 12px 24px;
            background-color: #007BFF;
            color: #ffffff;
            text-decoration: none;
            border-radius: 4px;
            transition: background-color 0.3s ease;
        }
        a.button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>欢迎访问！</h1>
        <p>要打开网站，请点击下方按钮。</p>
        <a href="https://qytnody.qingyunti.cc" class="button">点击前往官网</a>
    </div>
</body>
</html>

2025-03-22 17:50:58 airport.py [line:276] INFO: achieved max retry when register, domain: https://svip.xingheyun.sbs
2025-03-22 17:50:59 airport.py [line:782] INFO: subconverter completed, artifact: [a02qytvipaffpro-8ymlf-8KD]	success=[False]
2025-03-22 17:51:00 airport.py [line:361] INFO: not exists free plan, domain: https://a.kpyun.live
2025-03-22 17:51:00 workflow.py [line:140] INFO: finished fetch proxy: name=[xueyejiasucom-wm61]	username=[XjbkRsfhK2@gmail.com]	domain=[http://xueyejiasu.com]	count=[12]
2025-03-22 17:51:01 airport.py [line:394] INFO: [RegisterSuccess] register successed, domain: https://www.kuaidog006.top
2025-03-22 17:51:02 utils.py [line:558] INFO: [Concurrent] multi-threaded execute [executewrapper] finished, count: 35, cost: 6.81s
2025-03-22 17:51:02 collect.py [line:384] INFO: found 12 proxies, save it to ['/home/runner/work/none/none/utils/airport/collectAirport/data/clash.yaml', '/home/runner/work/none/none/utils/airport/collectAirport/data/v2ray.txt']
2025-03-22 17:51:03 push.py [line:100] ERROR: [PushError]: group=[collect], name: gist, error message: 
Traceback (most recent call last):
  File "/home/runner/work/none/none/utils/airport/collectAirport/subscribe/push.py", line 72, in push_to
    response = urllib.request.urlopen(request, timeout=60, context=utils.CTX)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 189, in urlopen
    return opener.open(url, data, timeout)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 495, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 604, in http_response
    response = self.parent.error(
        'http', request, response, code, msg, hdrs)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 533, in error
    return self._call_chain(*args)
           ~~~~~~~~~~~~~~~~^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 613, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 422: Unprocessable Entity

2025-03-22 17:51:03 push.py [line:100] ERROR: [PushError]: group=[collect], name: gist, error message: 
Traceback (most recent call last):
  File "/home/runner/work/none/none/utils/airport/collectAirport/subscribe/push.py", line 72, in push_to
    response = urllib.request.urlopen(request, timeout=60, context=utils.CTX)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 189, in urlopen
    return opener.open(url, data, timeout)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 495, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 604, in http_response
    response = self.parent.error(
        'http', request, response, code, msg, hdrs)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 533, in error
    return self._call_chain(*args)
           ~~~~~~~~~~~~~~~~^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 613, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 422: Unprocessable Entity

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/none/none/utils/airport/collectAirport/subscribe/push.py", line 72, in push_to
    response = urllib.request.urlopen(request, timeout=60, context=utils.CTX)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 189, in urlopen
    return opener.open(url, data, timeout)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 495, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 604, in http_response
    response = self.parent.error(
        'http', request, response, code, msg, hdrs)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 533, in error
    return self._call_chain(*args)
           ~~~~~~~~~~~~~~~~^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 613, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 422: Unprocessable Entity

2025-03-22 17:51:03 push.py [line:100] ERROR: [PushError]: group=[collect], name: gist, error message: 
Traceback (most recent call last):
  File "/home/runner/work/none/none/utils/airport/collectAirport/subscribe/push.py", line 72, in push_to
    response = urllib.request.urlopen(request, timeout=60, context=utils.CTX)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 189, in urlopen
    return opener.open(url, data, timeout)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 495, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 604, in http_response
    response = self.parent.error(
        'http', request, response, code, msg, hdrs)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 533, in error
    return self._call_chain(*args)
           ~~~~~~~~~~~~~~~~^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 613, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 422: Unprocessable Entity

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/none/none/utils/airport/collectAirport/subscribe/push.py", line 72, in push_to
    response = urllib.request.urlopen(request, timeout=60, context=utils.CTX)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 189, in urlopen
    return opener.open(url, data, timeout)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 495, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 604, in http_response
    response = self.parent.error(
        'http', request, response, code, msg, hdrs)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 533, in error
    return self._call_chain(*args)
           ~~~~~~~~~~~~~~~~^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 613, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 422: Unprocessable Entity

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/none/none/utils/airport/collectAirport/subscribe/push.py", line 72, in push_to
    response = urllib.request.urlopen(request, timeout=60, context=utils.CTX)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 189, in urlopen
    return opener.open(url, data, timeout)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 495, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 604, in http_response
    response = self.parent.error(
        'http', request, response, code, msg, hdrs)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 533, in error
    return self._call_chain(*args)
           ~~~~~~~~~~~~~~~~^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 613, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 422: Unprocessable Entity

2025-03-22 17:51:03 push.py [line:100] ERROR: [PushError]: group=[collect], name: gist, error message: 
Traceback (most recent call last):
  File "/home/runner/work/none/none/utils/airport/collectAirport/subscribe/push.py", line 72, in push_to
    response = urllib.request.urlopen(request, timeout=60, context=utils.CTX)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 189, in urlopen
    return opener.open(url, data, timeout)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 495, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 604, in http_response
    response = self.parent.error(
        'http', request, response, code, msg, hdrs)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 533, in error
    return self._call_chain(*args)
           ~~~~~~~~~~~~~~~~^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 613, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 422: Unprocessable Entity

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/none/none/utils/airport/collectAirport/subscribe/push.py", line 72, in push_to
    response = urllib.request.urlopen(request, timeout=60, context=utils.CTX)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 189, in urlopen
    return opener.open(url, data, timeout)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 495, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 604, in http_response
    response = self.parent.error(
        'http', request, response, code, msg, hdrs)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 533, in error
    return self._call_chain(*args)
           ~~~~~~~~~~~~~~~~^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 613, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 422: Unprocessable Entity

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/none/none/utils/airport/collectAirport/subscribe/push.py", line 72, in push_to
    response = urllib.request.urlopen(request, timeout=60, context=utils.CTX)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 189, in urlopen
    return opener.open(url, data, timeout)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 495, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 604, in http_response
    response = self.parent.error(
        'http', request, response, code, msg, hdrs)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 533, in error
    return self._call_chain(*args)
           ~~~~~~~~~~~~~~~~^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 613, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 422: Unprocessable Entity

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/none/none/utils/airport/collectAirport/subscribe/push.py", line 72, in push_to
    response = urllib.request.urlopen(request, timeout=60, context=utils.CTX)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 189, in urlopen
    return opener.open(url, data, timeout)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 495, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 604, in http_response
    response = self.parent.error(
        'http', request, response, code, msg, hdrs)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 533, in error
    return self._call_chain(*args)
           ~~~~~~~~~~~~~~~~^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 613, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 422: Unprocessable Entity

2025-03-22 17:51:04 push.py [line:100] ERROR: [PushError]: group=[collect], name: gist, error message: 
Traceback (most recent call last):
  File "/home/runner/work/none/none/utils/airport/collectAirport/subscribe/push.py", line 72, in push_to
    response = urllib.request.urlopen(request, timeout=60, context=utils.CTX)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 189, in urlopen
    return opener.open(url, data, timeout)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 495, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 604, in http_response
    response = self.parent.error(
        'http', request, response, code, msg, hdrs)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 533, in error
    return self._call_chain(*args)
           ~~~~~~~~~~~~~~~~^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 613, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 422: Unprocessable Entity

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/none/none/utils/airport/collectAirport/subscribe/push.py", line 72, in push_to
    response = urllib.request.urlopen(request, timeout=60, context=utils.CTX)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 189, in urlopen
    return opener.open(url, data, timeout)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 495, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 604, in http_response
    response = self.parent.error(
        'http', request, response, code, msg, hdrs)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 533, in error
    return self._call_chain(*args)
           ~~~~~~~~~~~~~~~~^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 613, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 422: Unprocessable Entity

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/none/none/utils/airport/collectAirport/subscribe/push.py", line 72, in push_to
    response = urllib.request.urlopen(request, timeout=60, context=utils.CTX)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 189, in urlopen
    return opener.open(url, data, timeout)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 495, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 604, in http_response
    response = self.parent.error(
        'http', request, response, code, msg, hdrs)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 533, in error
    return self._call_chain(*args)
           ~~~~~~~~~~~~~~~~^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 613, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 422: Unprocessable Entity

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/none/none/utils/airport/collectAirport/subscribe/push.py", line 72, in push_to
    response = urllib.request.urlopen(request, timeout=60, context=utils.CTX)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 189, in urlopen
    return opener.open(url, data, timeout)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 495, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 604, in http_response
    response = self.parent.error(
        'http', request, response, code, msg, hdrs)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 533, in error
    return self._call_chain(*args)
           ~~~~~~~~~~~~~~~~^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 613, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 422: Unprocessable Entity

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/none/none/utils/airport/collectAirport/subscribe/push.py", line 72, in push_to
    response = urllib.request.urlopen(request, timeout=60, context=utils.CTX)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 189, in urlopen
    return opener.open(url, data, timeout)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 495, in open
    response = meth(req, response)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 604, in http_response
    response = self.parent.error(
        'http', request, response, code, msg, hdrs)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 533, in error
    return self._call_chain(*args)
           ~~~~~~~~~~~~~~~~^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/urllib/request.py", line 613, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 422: Unprocessable Entity

2025-03-22 17:51:04 collect.py [line:441] ERROR: upload proxies and subscriptions to gist failed
